apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: rag1-may7-1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rag1-may7-1
  name: rag1-may7-1
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi
